source 'https://rubygems.org'

gem 'prawn'
gem 'prawn-qrcode', :git => 'https://github.com/jabbrwcky/prawn-qrcode'
gem 'prawn-svg'
gem 'color'
gem 'rmagick'
gem 'json'
gem 'nokogiri'
gem 'pry'
gem 'rest-client'
